//HookD3D12ReplacementCreation.cpp
#include <cstdint>
#include <string>
#include <vector>

//custom
#include "HookD3D12.h"
#include "HookD3D12PipelineUtils.h"
#include "HookD3D12ReplacementLookup.h"
#include "HookD3D12ReplacementTemplates.h"
#include "Hash.h"
#include "ShaderInjectorGUI.h"
#include "ShaderInjectorIO.h"
#include "ShaderReplacement.h"
#include "StringHelper.h"

namespace HookD3D12
{
	namespace
	{
		bool CreateReplacementShaderTemplate(
			const std::string& sourceList,
			int pipelineIndex,
			ShaderReplacement::ShaderType shaderType,
			uint64_t shaderHash,
			size_t shaderBytecodeLength,
			const void* shaderBytecode,
			ID3D12PipelineState* pipelineState,
			const GraphicsPipelineInfo* graphicsInfo,
			const PipelineStateInfo* streamInfo)
		{
			if (!shaderHash || !shaderBytecode || shaderBytecodeLength == 0)
			{
				ShaderInjectorGUI::WriteToRuntimeLogError("HookD3D12ReplacementCreation->CreateReplacementShaderTemplate: missing shader bytecode");
				return false;
			}

			const std::string hashText = Hash::FormatHash(shaderHash);
			const std::string shaderTypeText = StringHelper::ShaderTypeToString(shaderType);
			const std::string replacementName = "ShaderReplacement_" + shaderTypeText + "_" + hashText;
			const std::string replacementDirectory = ShaderInjectorIO::JoinPath(ShaderInjectorIO::GetShaderReplacementsDirectory(), replacementName);

			if (!ShaderInjectorIO::DirectoryExists(replacementDirectory))
				ShaderInjectorIO::DirectoryCreate(replacementDirectory);

			if (!ShaderInjectorIO::DirectoryExists(replacementDirectory))
			{
				ShaderInjectorGUI::WriteToRuntimeLogError("HookD3D12ReplacementCreation->CreateReplacementShaderTemplate: failed to create directory " + replacementDirectory);
				return false;
			}

			ShaderReplacement::ShaderReplacementDisk replacement{};
			replacement.schemaVersion = 1;
			// Replacements remain enabled unless the user explicitly disables them.
			// Matching safety is enforced by exact hashes and verified blob content.
			replacement.enabled = true;
			replacement.name = replacementName;
			replacement.shaderType = shaderType;
			replacement.shaderProfile = StringHelper::ShaderProfileForType(shaderType);
			replacement.shaderEntryPoint = "main";
			replacement.originalShaderBytecodeHash = hashText;
			replacement.originalShaderBytecodeLength = std::to_string(shaderBytecodeLength);
			replacement.replacementDirectory = replacementDirectory;
			replacement.originalShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalShaderBytecode" + ShaderInjectorIO::extensionBIN);
			replacement.modifiedShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "NewCompiledBlob" + ShaderInjectorIO::extensionBLOB);
			replacement.jsonPath = ShaderInjectorIO::JoinPath(replacementDirectory, "ShaderReplacement" + ShaderInjectorIO::extensionJSON);
			replacement.sourceList = sourceList;
			replacement.pipelineIndex = std::to_string(pipelineIndex);
			replacement.pipelineStateType = sourceList == "Stream" ? "PipelineStateStream" : "GraphicsPipelineStateDesc";
			replacement.psoPointer = StringHelper::PointerToString(pipelineState);

			uint64_t cachedBlobHash = 0;
			SIZE_T cachedBlobSize = 0;
			std::vector<uint8_t> cachedBlob;

			if (GetPipelineCachedBlobInfo(pipelineState, cachedBlobHash, cachedBlobSize, &cachedBlob))
			{
				replacement.pipelineCachedBlobHash = Hash::FormatHash(cachedBlobHash);
				replacement.pipelineCachedBlobLength = std::to_string(cachedBlobSize);
				replacement.pipelineCachedBlobPath = ShaderInjectorIO::JoinPath(replacement.replacementDirectory, "OriginalPipelineCachedBlob" + ShaderInjectorIO::extensionBIN);
			}

			replacement.targetSubobjectType = std::to_string((UINT)SubobjectTypeForShaderType(shaderType));
			replacement.notes = "Generated by Shader Injector. Sidecar paths are stored as filenames and resolved relative to this JSON file at runtime. Shader source resolves from ShaderSources/<shader type>s.";

			if (graphicsInfo)
			{
				FillCommonReplacementHashes(replacement, graphicsInfo->vsHash, graphicsInfo->psHash, 0, graphicsInfo->gsHash, graphicsInfo->hsHash, graphicsInfo->dsHash);
				FillGraphicsReplacementPortableState(replacement, *graphicsInfo);

				std::vector<uint8_t> rootSignatureBlob;
				uint64_t rootSignatureHash = 0;

				if (GetRootSignatureBlob(graphicsInfo->originalDesc.pRootSignature, rootSignatureBlob, rootSignatureHash))
				{
					replacement.rootSignatureHash = Hash::FormatHash(rootSignatureHash);
					replacement.rootSignatureLength = std::to_string(rootSignatureBlob.size());
				}
			}
			else if (streamInfo)
			{
				FillCommonReplacementHashes(replacement, streamInfo->vsHash, streamInfo->psHash, streamInfo->csHash, streamInfo->gsHash, streamInfo->hsHash, streamInfo->dsHash);
				FillStreamReplacementPortableStateFromBlob(replacement, *streamInfo);

				if (!streamInfo->streamBlob.empty())
					replacement.pipelineStreamBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "PipelineStateStream" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->streamBlob.empty())
					replacement.pipelineStreamMetadataPath = ShaderInjectorIO::JoinPath(replacementDirectory, "PipelineStateStreamMetadata" + ShaderInjectorIO::extensionJSON);

				std::vector<uint8_t> rootSignatureBlob;
				uint64_t rootSignatureHash = 0;

				if (GetRootSignatureBlob(streamInfo->rootSignature, rootSignatureBlob, rootSignatureHash))
				{
					replacement.rootSignatureHash = Hash::FormatHash(rootSignatureHash);
					replacement.rootSignatureLength = std::to_string(rootSignatureBlob.size());
					replacement.rootSignatureBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "RootSignatureBlob" + ShaderInjectorIO::extensionBIN);
				}

				if (!streamInfo->vsBytecode.empty())
					replacement.vertexShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalVertexShaderBytecode" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->psBytecode.empty())
					replacement.pixelShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalPixelShaderBytecode" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->csBytecode.empty())
					replacement.computeShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalComputeShaderBytecode" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->gsBytecode.empty())
					replacement.geometryShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalGeometryShaderBytecode" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->hsBytecode.empty())
					replacement.hullShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalHullShaderBytecode" + ShaderInjectorIO::extensionBIN);

				if (!streamInfo->dsBytecode.empty())
					replacement.domainShaderBlobPath = ShaderInjectorIO::JoinPath(replacementDirectory, "OriginalDomainShaderBytecode" + ShaderInjectorIO::extensionBIN);
			}

			bool ok = true;
			ok = ShaderInjectorIO::WriteBinaryFile(replacement.originalShaderBlobPath, shaderBytecode, shaderBytecodeLength) && ok;

			if (!cachedBlob.empty() && !replacement.pipelineCachedBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.pipelineCachedBlobPath, cachedBlob.data(), cachedBlob.size()) && ok;

			if (streamInfo && !streamInfo->streamBlob.empty() && !replacement.pipelineStreamBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.pipelineStreamBlobPath, streamInfo->streamBlob.data(), streamInfo->streamBlob.size()) && ok;

			if (streamInfo && !replacement.pipelineStreamMetadataPath.empty())
			{
				ShaderReplacement::ShaderPipelineStreamMetadataDisk metadata = BuildPipelineStreamMetadata(*streamInfo);
				ok = ShaderReplacement::WritePipelineStreamMetadataJson(replacement.pipelineStreamMetadataPath, metadata) && ok;
			}

			if (streamInfo && !replacement.rootSignatureBlobPath.empty())
			{
				std::vector<uint8_t> rootSignatureBlob;
				uint64_t rootSignatureHash = 0;
				if (GetRootSignatureBlob(streamInfo->rootSignature, rootSignatureBlob, rootSignatureHash))
					ok = ShaderInjectorIO::WriteBinaryFile(replacement.rootSignatureBlobPath, rootSignatureBlob.data(), rootSignatureBlob.size()) && ok;
			}

			if (streamInfo && !streamInfo->vsBytecode.empty() && !replacement.vertexShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.vertexShaderBlobPath, streamInfo->vsBytecode.data(), streamInfo->vsBytecode.size()) && ok;

			if (streamInfo && !streamInfo->psBytecode.empty() && !replacement.pixelShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.pixelShaderBlobPath, streamInfo->psBytecode.data(), streamInfo->psBytecode.size()) && ok;

			if (streamInfo && !streamInfo->csBytecode.empty() && !replacement.computeShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.computeShaderBlobPath, streamInfo->csBytecode.data(), streamInfo->csBytecode.size()) && ok;

			if (streamInfo && !streamInfo->gsBytecode.empty() && !replacement.geometryShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.geometryShaderBlobPath, streamInfo->gsBytecode.data(), streamInfo->gsBytecode.size()) && ok;

			if (streamInfo && !streamInfo->hsBytecode.empty() && !replacement.hullShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.hullShaderBlobPath, streamInfo->hsBytecode.data(), streamInfo->hsBytecode.size()) && ok;

			if (streamInfo && !streamInfo->dsBytecode.empty() && !replacement.domainShaderBlobPath.empty())
				ok = ShaderInjectorIO::WriteBinaryFile(replacement.domainShaderBlobPath, streamInfo->dsBytecode.data(), streamInfo->dsBytecode.size()) && ok;

			if (streamInfo)
				WriteMatchingStreamPipelineTemplateVariants(replacement, shaderType, shaderHash, ok);

			ok = ShaderInjectorIO::GenerateShaderTextDXIL(replacement.originalShaderBlobPath) && ok;
			ok = ShaderReplacement::WriteShaderReplacementJson(replacement) && ok;

			if (!ok)
			{
				ShaderInjectorGUI::WriteToRuntimeLogError("HookD3D12ReplacementCreation->CreateReplacementShaderTemplate: failed to write one or more files for " + replacementName);
				return false;
			}

			ShaderInjectorGUI::WriteToRuntimeLog("HookD3D12ReplacementCreation->CreateReplacementShaderTemplate: Created replacement shader template: " + replacement.jsonPath);
			gLoadedShaderReplacementsOnce = false;
			MarkShaderReplacementApplyDirty();
			return true;
		}
	}

	bool CreateReplacementShaderTemplateForPipeline(
		const std::string& sourceList,
		int pipelineIndex,
		ShaderReplacement::ShaderType shaderType,
		uint64_t shaderHash,
		size_t shaderBytecodeLength,
		const void* shaderBytecode,
		GraphicsPipelineInfo& pipeline)
	{
		return CreateReplacementShaderTemplate(sourceList, pipelineIndex, shaderType, shaderHash, shaderBytecodeLength, shaderBytecode, pipeline.pipelineState, &pipeline, nullptr);
	}

	bool CreateReplacementShaderTemplateForPipeline(
		const std::string& sourceList,
		int pipelineIndex,
		ShaderReplacement::ShaderType shaderType,
		uint64_t shaderHash,
		size_t shaderBytecodeLength,
		const void* shaderBytecode,
		PipelineStateInfo& pipeline)
	{
		return CreateReplacementShaderTemplate(sourceList, pipelineIndex, shaderType, shaderHash, shaderBytecodeLength, shaderBytecode, pipeline.pipelineState, nullptr, &pipeline);
	}
}
