// ShaderInjectorVersion.h
#pragma once

#define SHADER_INJECTOR_VERSION_MAJOR 2
#define SHADER_INJECTOR_VERSION_MINOR 1
#define SHADER_INJECTOR_VERSION_PATCH 0
#define SHADER_INJECTOR_VERSION_BUILD 0

#define SHADER_INJECTOR_VERSION_NUMERIC \
	SHADER_INJECTOR_VERSION_MAJOR, SHADER_INJECTOR_VERSION_MINOR, SHADER_INJECTOR_VERSION_PATCH, SHADER_INJECTOR_VERSION_BUILD

#define SHADER_INJECTOR_VERSION_STRING "2.1.0.0"
