#include "ShaderResource/ShaderResource.h"

namespace ShaderResource
{
	#define SHADER_INJECTOR_DXGI_FORMAT(name, value) \
		TextureFormatOption{ value, #name, #name " (" #value ")" }

	const std::vector<TextureFormatOption>& TextureFormatOptions()
	{
		// Keep numeric values here rather than depending on a particular Windows SDK
		// version so configurations containing newer DXGI formats remain portable.
		static const std::vector<TextureFormatOption> formatOptions = {
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_UNKNOWN, 0),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32A32_TYPELESS, 1),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32A32_FLOAT, 2),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32A32_UINT, 3),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32A32_SINT, 4),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32_TYPELESS, 5),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32_FLOAT, 6),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32_UINT, 7),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32B32_SINT, 8),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_TYPELESS, 9),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_FLOAT, 10),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_UNORM, 11),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_UINT, 12),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_SNORM, 13),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16B16A16_SINT, 14),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32_TYPELESS, 15),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32_FLOAT, 16),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32_UINT, 17),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G32_SINT, 18),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32G8X24_TYPELESS, 19),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_D32_FLOAT_S8X24_UINT, 20),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, 21),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_X32_TYPELESS_G8X24_UINT, 22),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R10G10B10A2_TYPELESS, 23),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R10G10B10A2_UNORM, 24),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R10G10B10A2_UINT, 25),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R11G11B10_FLOAT, 26),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_TYPELESS, 27),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_UNORM, 28),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, 29),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_UINT, 30),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_SNORM, 31),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8B8A8_SINT, 32),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_TYPELESS, 33),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_FLOAT, 34),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_UNORM, 35),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_UINT, 36),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_SNORM, 37),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16G16_SINT, 38),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32_TYPELESS, 39),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_D32_FLOAT, 40),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32_FLOAT, 41),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32_UINT, 42),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R32_SINT, 43),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R24G8_TYPELESS, 44),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_D24_UNORM_S8_UINT, 45),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R24_UNORM_X8_TYPELESS, 46),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_X24_TYPELESS_G8_UINT, 47),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_TYPELESS, 48),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_UNORM, 49),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_UINT, 50),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_SNORM, 51),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_SINT, 52),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_TYPELESS, 53),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_FLOAT, 54),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_D16_UNORM, 55),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_UNORM, 56),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_UINT, 57),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_SNORM, 58),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R16_SINT, 59),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8_TYPELESS, 60),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8_UNORM, 61),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8_UINT, 62),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8_SNORM, 63),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8_SINT, 64),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_A8_UNORM, 65),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R1_UNORM, 66),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R9G9B9E5_SHAREDEXP, 67),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R8G8_B8G8_UNORM, 68),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_G8R8_G8B8_UNORM, 69),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC1_TYPELESS, 70),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC1_UNORM, 71),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC1_UNORM_SRGB, 72),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC2_TYPELESS, 73),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC2_UNORM, 74),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC2_UNORM_SRGB, 75),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC3_TYPELESS, 76),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC3_UNORM, 77),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC3_UNORM_SRGB, 78),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC4_TYPELESS, 79),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC4_UNORM, 80),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC4_SNORM, 81),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC5_TYPELESS, 82),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC5_UNORM, 83),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC5_SNORM, 84),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B5G6R5_UNORM, 85),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B5G5R5A1_UNORM, 86),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8A8_UNORM, 87),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8X8_UNORM, 88),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM, 89),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8A8_TYPELESS, 90),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, 91),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8X8_TYPELESS, 92),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B8G8R8X8_UNORM_SRGB, 93),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC6H_TYPELESS, 94),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC6H_UF16, 95),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC6H_SF16, 96),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC7_TYPELESS, 97),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC7_UNORM, 98),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_BC7_UNORM_SRGB, 99),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_AYUV, 100),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_Y410, 101),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_Y416, 102),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_NV12, 103),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_P010, 104),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_P016, 105),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_420_OPAQUE, 106),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_YUY2, 107),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_Y210, 108),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_Y216, 109),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_NV11, 110),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_AI44, 111),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_IA44, 112),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_P8, 113),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_A8P8, 114),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_B4G4R4A4_UNORM, 115),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_P208, 130),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_V208, 131),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_V408, 132),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE, 189),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE, 190),
			SHADER_INJECTOR_DXGI_FORMAT(DXGI_FORMAT_A4B4G4R4_UNORM, 191),
		};
		return formatOptions;
	}

	std::string TextureFormatDisplayName(uint32_t format)
	{
		for (const TextureFormatOption& option : TextureFormatOptions())
		{
			if (option.value == format)
				return option.displayName;
		}

		return "Unknown DXGI format (" + std::to_string(format) + ")";
	}

	const char* ResourceOriginName(ResourceOrigin origin)
	{
		switch (origin)
		{
			case ResourceOrigin::Game: return "Game Runtime";
			case ResourceOrigin::Runtime: return "Injector Runtime";
			case ResourceOrigin::Disk:
			default: return "Offline / Disk";
		}
	}

	const char* ResourceLifetimeName(ResourceLifetime lifetime)
	{
		switch (lifetime)
		{
			case ResourceLifetime::Transient: return "Transient";
			case ResourceLifetime::Persistent: return "Persistent";
			case ResourceLifetime::History: return "History";
			case ResourceLifetime::Immutable:
			default: return "Immutable";
		}
	}

	bool IsValidDownscaleFactor(uint32_t downscaleFactor)
	{
		return downscaleFactor >= 1 && downscaleFactor <= 16 &&
			(downscaleFactor & (downscaleFactor - 1)) == 0;
	}

	#undef SHADER_INJECTOR_DXGI_FORMAT
}
